name: Build and release

on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: python -m pip install conan
      - run: |
          conan profile detect
          conan profile show -pr default
      - run: |
          chmod +x install-dependencies-with-conan.sh
          CONAN_ADD_ARGS="-c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=true" ./install-dependencies-with-conan.sh
      - run: |
          chmod +x build-with-local-cc.sh 
          ./build-with-local-cc.sh
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*-local-cc-Release/sources/raytracerui/raytracerui.exe
