name: Build and release

on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          chmod +x build-with-local-cc.sh 
          ./build-with-local-cc.sh
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*-local-cc-Release/sources/raytracerui/raytracerui.exe
